export enum ArgumentType {
  NO_ARGUMENTS = 0,
  ONE_IMMEDIATE = 1,
  TWO_IMMEDIATE = 2,
  ONE_OFFSET = 3,
  ONE_REGISTER_ONE_IMMEDIATE = 4,
  ONE_REGISTER_TWO_IMMEDIATE = 5,
  ONE_REGISTER_ONE_IMMEDIATE_ONE_OFFSET = 6,
  TWO_REGISTERS = 7,
  TWO_REGISTERS_ONE_IMMEDIATE = 8,
  TWO_REGISTERS_ONE_OFFSET = 9,
  TWO_REGISTERS_TWO_IMMEDIATE = 10,
  THREE_REGISTERS = 11,
}
